/* Generated By:JJTree: Do not edit this line. ASTAndNode.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTAndNode.h"
#include "Boolean.h"

  
  ASTAndNode::ASTAndNode(int id) : SimpleNode(id) {
  }
  ASTAndNode::ASTAndNode(SPLParser *parser, int id) : SimpleNode(parser, id) {
  }
  ASTAndNode::~ASTAndNode() {
  }
  void ASTAndNode::interpret()
  {
     jjtGetChild(0)->interpret();

	 const Node* top = stack.top();
	 if (typeid(*top) == typeid(Boolean)) {
		 const Boolean* boolean = (Boolean*)top;
		 if (!*boolean) {
			 stack.push(new Boolean(false));
			 return;
		 }
	 }
     jjtGetChild(1)->interpret();
 
	 unique_ptr<Boolean> left((Boolean*)stack.top()); stack.pop();
	 unique_ptr<Boolean> right((Boolean*)stack.top()); stack.pop();
     stack.push(new Boolean(*left && *right));
  }


