/* Generated By:JJTree: Do not edit this line. ASTBitwiseOrNode.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTBitwiseOrNode.h"
#include "Boolean.h"
#include "Integer.h"

  
  ASTBitwiseOrNode::ASTBitwiseOrNode(int id) : SimpleNode(id) {
  }
  ASTBitwiseOrNode::ASTBitwiseOrNode(SPLParser *parser, int id) : SimpleNode(parser, id) {
  }
  ASTBitwiseOrNode::~ASTBitwiseOrNode() {
  }


  void ASTBitwiseOrNode::interpret()
  {
     jjtGetChild(0)->interpret();
     jjtGetChild(1)->interpret();

	 const Node* top = stack.top();
	 if (typeid(*top) == typeid(Boolean)) {
		 unique_ptr<Boolean> left((Boolean*)stack.top()); stack.pop();
		 unique_ptr<Boolean> righ((Boolean*)stack.top()); stack.pop();
		 stack.push(new Boolean(*left | *righ));
	 }
	 if (typeid(*top) == typeid(Integer)) {
		 unique_ptr<Integer> left((Integer*)stack.top()); stack.pop();
		 unique_ptr<Integer> righ((Integer*)stack.top()); stack.pop();
		 stack.push(new Integer(*left | *righ));
	 }
  }
