/* Generated By:JJTree: Do not edit this line. ASTCompilationUnit.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include <iostream>
using namespace std;

#include "ASTCompilationUnit.h"

  
  ASTCompilationUnit::ASTCompilationUnit(int id) : SimpleNode(id) {
  }
  ASTCompilationUnit::ASTCompilationUnit(SPLParser *parser, int id) : SimpleNode(parser, id) {
  }
  ASTCompilationUnit::~ASTCompilationUnit() {
  }
  void ASTCompilationUnit::interpret()
  {
     int i, k = jjtGetNumChildren();

     for (i = 0; i < k; i++)
     {
	cout << "Executing:" << endl;
	Token* first  = ((SimpleNode*)jjtGetChild(i))->jjtGetFirstToken();
	Token* last = ((SimpleNode*)jjtGetChild(i))->jjtGetLastToken();
	for (Token* t = first; t != nullptr; t = t->next)
	{
	    cout << " " << t->toString();

	    if (t == last)
	    	break;
	}
	cout << endl;

        jjtGetChild(i)->interpret();
     }

  }


