/* Generated By:JJTree: Do not edit this line. ASTDivNode.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTDivNode.h"
#include "Integer.h"

  
  ASTDivNode::ASTDivNode(int id) : SimpleNode(id) {
  }
  ASTDivNode::ASTDivNode(SPLParser *parser, int id) : SimpleNode(parser, id) {
  }
  ASTDivNode::~ASTDivNode() {
  }

  void ASTDivNode::interpret()
  {
     jjtGetChild(0)->interpret();
     jjtGetChild(1)->interpret();

	 unique_ptr<Integer> left((Integer*)stack.top()); stack.pop();
	 unique_ptr<Integer> right((Integer*)stack.top()); stack.pop();
	 stack.push(*left / *right);
  }

