/* Generated By:JJTree: Do not edit this line. ASTFalseNode.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTFalseNode.h"
#include "Boolean.h"

  
  ASTFalseNode::ASTFalseNode(int id) : SimpleNode(id) {
  }
  ASTFalseNode::ASTFalseNode(SPLParser *parser, int id) : SimpleNode(parser, id) {
  }
  ASTFalseNode::~ASTFalseNode() {
  }

  void ASTFalseNode::interpret()
  {
     stack.push(new Boolean(false));
  }

