/* Generated By:JJTree: Do not edit this line. ASTGTNode.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#pragma once

#include "SimpleNode.h"


class SPLParser;


class ASTGTNode : public SimpleNode {
public: 
           ASTGTNode(int id);
           ASTGTNode(SPLParser *parser, int id);
  virtual ~ASTGTNode();
  virtual void interpret();

};

