/* Generated By:JJTree: Do not edit this line. ASTStatementExpression.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTStatementExpression.h"

  
  ASTStatementExpression::ASTStatementExpression(int id) : SimpleNode(id) {
  }
  ASTStatementExpression::ASTStatementExpression(SPLParser *parser, int id) : SimpleNode(parser, id) {
  }
  ASTStatementExpression::~ASTStatementExpression() {
  }

  void ASTStatementExpression::interpret()
  {
     jjtGetChild(0)->interpret();
     stack.pop(); //just throw away the value.
  }

