/* Generated By:JJTree: Do not edit this line. ASTAssignment.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTAssignment.h"
#include "ASTId.h"

  
  ASTAssignment::ASTAssignment(int id) : SimpleNode(id) {
  }
  ASTAssignment::ASTAssignment(SPLParser *parser, int id) : SimpleNode(parser, id) {
  }
  ASTAssignment::~ASTAssignment() {
  }

  void ASTAssignment::interpret()
  {
     string name;

     jjtGetChild(1)->interpret();
	 //    symtab.put(name = ((ASTId)jjtGetChild(0)).name, stack[top]);
	 Node* top = stack.top();
	 name =  ((ASTId*)jjtGetChild(0))->name;
     symtab[name] = top;
  }

