/* Generated By:JJTree: Do not edit this line. ASTCompilationUnit.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTCompilationUnit.h"

  
  ASTCompilationUnit::ASTCompilationUnit(int id) : SimpleNode(id) {
  }
  ASTCompilationUnit::ASTCompilationUnit(SPLParser *parser, int id) : SimpleNode(parser, id) {
  }
  ASTCompilationUnit::~ASTCompilationUnit() {
  }
  void ASTCompilationUnit::interpret()
  {
     int i, k = jjtGetNumChildren();

     for (i = 0; i < k; i++)
     {
	System.out.print("Executing:");
	Token first  = ((SimpleNode)jjtGetChild(i)).jjtGetFirstToken();
	Token last = ((SimpleNode)jjtGetChild(i)).jjtGetLastToken();
	for (Token t = first; t != null; t = t.next)
	{
	    System.out.print(" " + t);

	    if (t == last)
	    	break;
	}
	System.out.println();

        jjtGetChild(i).interpret();
     }

  }


