/* Generated By:JJTree: Do not edit this line. ASTGTNode.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTGTNode.h"
#include "Boolean.h"
#include "Integer.h"

  
  ASTGTNode::ASTGTNode(int id) : SimpleNode(id) {
  }
  ASTGTNode::ASTGTNode(SPLParser *parser, int id) : SimpleNode(parser, id) {
  }
  ASTGTNode::~ASTGTNode() {
  }


  void ASTGTNode::interpret()
  {
     jjtGetChild(0)->interpret();
     jjtGetChild(1)->interpret();

     stack[--top] = new Boolean(((Integer)stack[top]).intValue() >
                                ((Integer)stack[top + 1]).intValue());
  }
