/* Generated By:JJTree: Do not edit this line. ASTIntConstNode.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTIntConstNode.h"

  
  ASTIntConstNode::ASTIntConstNode(int id) : SimpleNode(id) {
  }
  ASTIntConstNode::ASTIntConstNode(SPLParser *parser, int id) : SimpleNode(parser, id) {
  }
  ASTIntConstNode::~ASTIntConstNode() {
  }

  void ASTIntConstNode::interpret()
  {
     stack[++top] = new Integer(val);
  }

