/* Generated By:JJTree: Do not edit this line. ASTOrNode.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTOrNode.h"
#include "Boolean.h"

  
  ASTOrNode::ASTOrNode(int id) : SimpleNode(id) {
  }
  ASTOrNode::ASTOrNode(SPLParser *parser, int id) : SimpleNode(parser, id) {
  }
  ASTOrNode::~ASTOrNode() {
  }

  void ASTOrNode::interpret()
  {
     jjtGetChild(0)->interpret();

	 const Node* top = stack.top();
	 if (typeid(*top) == typeid(Boolean))
     {
        stack.push(new Boolean(true));
        return;
     }

     jjtGetChild(1)->interpret();
	 unique_ptr<Boolean> left((Boolean*)stack.top()); stack.pop();
	 unique_ptr<Boolean> right((Boolean*)stack.top()); stack.pop();
	 stack.push(*left || *right);
  }

