/* Generated By:JJTree: Do not edit this line. ASTTrueNode.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTTrueNode.h"

  
  ASTTrueNode::ASTTrueNode(int id) : SimpleNode(id) {
  }
  ASTTrueNode::ASTTrueNode(SPLParser *parser, int id) : SimpleNode(parser, id) {
  }
  ASTTrueNode::~ASTTrueNode() {
  }

  void ASTTrueNode::interpret()
  {
     stack[++top] = new Boolean(true);
  }

