/* Generated By:JJTree: Do not edit this line. ASTVarDeclaration.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTVarDeclaration.h"
#include "Boolean.h"
#include "Integer.h"

  
  ASTVarDeclaration::ASTVarDeclaration(int id) : SimpleNode(id) {
  }
  ASTVarDeclaration::ASTVarDeclaration(SPLParser *parser, int id) : SimpleNode(parser, id) {
  }
  ASTVarDeclaration::~ASTVarDeclaration() {
  }


  void ASTVarDeclaration::interpret()
  {
     if (type == BOOL)
        symtab.put(name, new Boolean(false));
     else
        symtab.put(name, new Integer(0));
  }
