/* Generated By:JJTree: Do not edit this line. ASTWhileStatement.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTWhileStatement.h"

  
  ASTWhileStatement::ASTWhileStatement(int id) : SimpleNode(id) {
  }
  ASTWhileStatement::ASTWhileStatement(SPLParser *parser, int id) : SimpleNode(parser, id) {
  }
  ASTWhileStatement::~ASTWhileStatement() {
  }


  void ASTWhileStatement::interpret()
  {
     do {
       jjtGetChild(0).interpret();

       if (((Boolean)stack[top--]).booleanValue())
          jjtGetChild(1).interpret();
       else
          break;
    } while (true);
  }
